#!/usr/bin/env python3
"""Encode verifier-ambiguous codec table words and emit constructor fixups."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import struct
import sys

HIT = re.compile(
    r"ERROR: embedded absolute address (?P<section>\S+)\+0x(?P<offset>[0-9a-fA-F]+) "
    r"(?P<value>0x[0-9a-fA-F]+) not in target pack allowlist"
)
MASK = 0xA5A5A5A5
ANCHORS = {
    ".rodata": "canopus_rodata_anchor",
    ".rodata.cst16": "canopus_rodata_cst16_anchor",
}


def parse_hits(text: str) -> list[dict[str, int | str]]:
    hits: list[dict[str, int | str]] = []
    errors: list[str] = []
    for line in text.splitlines():
        if "ERROR:" not in line:
            continue
        if "undefined symbol 'canopus_decode_opaque_words'" in line:
            # The preliminary link intentionally omits the generated fixup
            # object; the final link must and does resolve this weak hook.
            continue
        match = HIT.search(line)
        if match is None:
            errors.append(line.strip())
            continue
        section = match.group("section")
        if section not in ANCHORS:
            errors.append(f"unsupported opaque-word section: {section}")
            continue
        value = int(match.group("value"), 16)
        encoded = value ^ MASK
        if 0x0C000000 <= encoded < 0x0C500000:
            errors.append(f"encoded word still aliases firmware: 0x{encoded:08x}")
            continue
        hits.append(
            {
                "section": section,
                "offset": int(match.group("offset"), 16),
                "value": value,
                "mask": MASK,
            }
        )
    if errors:
        raise SystemExit("\n".join(errors))
    unique = {(hit["section"], hit["offset"]): hit for hit in hits}
    return [unique[key] for key in sorted(unique)]


def generate(args: argparse.Namespace) -> None:
    hits = parse_hits(pathlib.Path(args.verifier_output).read_text())
    if not hits:
        raise SystemExit("verifier reported no opaque codec words")
    lines = [
        "/* Generated by encode-codec-words.py; do not edit. */",
        "#include <stdint.h>",
        "",
    ]
    for anchor in sorted({ANCHORS[str(hit["section"])] for hit in hits}):
        lines.append(f"extern const uint8_t {anchor}[];")
    lines.extend(
        [
            "",
            "struct canopus_opaque_fixup {",
            "    volatile uint32_t *word;",
            "    uint32_t mask;",
            "};",
            "",
            "__attribute__((section(\".data.canopus_fixups\"), used))",
            "static struct canopus_opaque_fixup canopus_opaque_fixups[] = {",
        ]
    )
    for hit in hits:
        anchor = ANCHORS[str(hit["section"])]
        lines.append(
            f"    {{(volatile uint32_t *)({anchor} + 0x{int(hit['offset']):x}), "
            f"0x{int(hit['mask']):08x}u}},"
        )
    lines.extend(
        [
            "};",
            "",
            "void canopus_decode_opaque_words(void)",
            "{",
            "    unsigned int i;",
            "    for (i = 0; i < (unsigned int)(sizeof(canopus_opaque_fixups) /",
            "                                    sizeof(canopus_opaque_fixups[0])); ++i) {",
            "        *canopus_opaque_fixups[i].word ^= canopus_opaque_fixups[i].mask;",
            "    }",
            "}",
            "",
        ]
    )
    pathlib.Path(args.output_c).write_text("\n".join(lines))
    pathlib.Path(args.metadata).write_text(json.dumps(hits, indent=2) + "\n")
    print(f"generated {len(hits)} codec-word fixups")


def elf_sections(data: bytearray) -> dict[str, tuple[int, int]]:
    if data[:4] != b"\x7fELF" or data[4] != 1 or data[5] != 1:
        raise SystemExit("expected ELF32 little-endian input")
    shoff = struct.unpack_from("<I", data, 32)[0]
    shentsize, shnum, shstrndx = struct.unpack_from("<HHH", data, 46)
    if shentsize < 40 or shstrndx >= shnum:
        raise SystemExit("invalid ELF section table")
    shstr = shoff + shstrndx * shentsize
    strings_offset, strings_size = struct.unpack_from("<II", data, shstr + 16)
    strings = data[strings_offset : strings_offset + strings_size]
    sections: dict[str, tuple[int, int]] = {}
    for index in range(shnum):
        header = shoff + index * shentsize
        name_offset = struct.unpack_from("<I", data, header)[0]
        end = strings.find(0, name_offset)
        if end < 0:
            raise SystemExit("unterminated ELF section name")
        name = bytes(strings[name_offset:end]).decode("ascii", "strict")
        file_offset, size = struct.unpack_from("<II", data, header + 16)
        sections[name] = (file_offset, size)
    return sections


def patch(args: argparse.Namespace) -> None:
    path = pathlib.Path(args.elf)
    data = bytearray(path.read_bytes())
    sections = elf_sections(data)
    hits = json.loads(pathlib.Path(args.metadata).read_text())
    for hit in hits:
        section = str(hit["section"])
        offset = int(hit["offset"])
        value = int(hit["value"])
        mask = int(hit["mask"])
        if section not in sections:
            raise SystemExit(f"missing ELF section: {section}")
        file_offset, size = sections[section]
        if offset + 4 > size:
            raise SystemExit(f"fixup outside {section}: 0x{offset:x}")
        current = struct.unpack_from("<I", data, file_offset + offset)[0]
        if current != value:
            raise SystemExit(
                f"codec word moved at {section}+0x{offset:x}: "
                f"expected 0x{value:08x}, found 0x{current:08x}"
            )
        struct.pack_into("<I", data, file_offset + offset, value ^ mask)
    path.write_bytes(data)
    print(f"encoded {len(hits)} codec words in {path}")


def main() -> None:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    gen = subparsers.add_parser("generate")
    gen.add_argument("--verifier-output", required=True)
    gen.add_argument("--output-c", required=True)
    gen.add_argument("--metadata", required=True)
    gen.set_defaults(run=generate)
    enc = subparsers.add_parser("patch")
    enc.add_argument("--elf", required=True)
    enc.add_argument("--metadata", required=True)
    enc.set_defaults(run=patch)
    args = parser.parse_args()
    args.run(args)


if __name__ == "__main__":
    main()
